FROM alpine:3.20

# Install system dependencies
RUN apk add --no-cache \
    python3 \
    py3-pip \
    redis \
    bash \
    git

# Set working directory
WORKDIR /app

# Copy application code
COPY . .
RUN chmod +x /app/docker-start.sh

RUN ls -l /app

RUN git clone https://github.com/asmirnov69/JupiterLI
RUN python3 -m venv venv
RUN /app/venv/bin/pip install /app/JupiterLI/
